import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final myThemeLight = ThemeData(
  useMaterial3: true,
  colorScheme: lightColorScheme,
  fontFamily: GoogleFonts.poppins().fontFamily,
  colorSchemeSeed: const Color(0xFF304D30),
  // appBarTheme: AppBarTheme(
  //   color: lightColorScheme.primary,
  //   titleTextStyle: const TextStyle(color: Colors.white, fontSize: 20),
  //   iconTheme: const IconThemeData(color: Colors.white),
  // )
);

final myThemeDark = ThemeData(
  useMaterial3: true,
  colorScheme: darkColorScheme,
  fontFamily: GoogleFonts.poppins().fontFamily,
);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006C45),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF8FF7BF),
  onPrimaryContainer: Color(0xFF002112),
  secondary: Color(0xFF4E6355),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD0E8D7),
  onSecondaryContainer: Color(0xFF0B1F15),
  tertiary: Color(0xFF3C6472),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFBFE9F9),
  onTertiaryContainer: Color(0xFF001F28),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFBFDF8),
  onBackground: Color(0xFF191C1A),
  surface: Color(0xFFFBFDF8),
  onSurface: Color(0xFF191C1A),
  surfaceVariant: Color(0xFFDCE5DC),
  onSurfaceVariant: Color(0xFF404943),
  outline: Color(0xFF707972),
  onInverseSurface: Color(0xFFEFF1ED),
  inverseSurface: Color(0xFF2E312E),
  inversePrimary: Color(0xFF73DAA4),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006C45),
  outlineVariant: Color(0xFFC0C9C1),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF73DAA4),
  onPrimary: Color(0xFF003822),
  primaryContainer: Color(0xFF005233),
  onPrimaryContainer: Color(0xFF8FF7BF),
  secondary: Color(0xFFB4CCBB),
  onSecondary: Color(0xFF203529),
  secondaryContainer: Color(0xFF364B3F),
  onSecondaryContainer: Color(0xFFD0E8D7),
  tertiary: Color(0xFFA4CDDD),
  onTertiary: Color(0xFF053542),
  tertiaryContainer: Color(0xFF234C59),
  onTertiaryContainer: Color(0xFFBFE9F9),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF191C1A),
  onBackground: Color(0xFFE1E3DF),
  surface: Color(0xFF191C1A),
  onSurface: Color(0xFFE1E3DF),
  surfaceVariant: Color(0xFF404943),
  onSurfaceVariant: Color(0xFFC0C9C1),
  outline: Color(0xFF8A938B),
  onInverseSurface: Color(0xFF191C1A),
  inverseSurface: Color(0xFFE1E3DF),
  inversePrimary: Color(0xFF006C45),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF73DAA4),
  outlineVariant: Color(0xFF404943),
  scrim: Color(0xFF000000),
);
